"""
Local SEO Geo-Gap Analyzer v2.7
Sprint 5.1 - Design DNA Extraction (Fixed)
- Sistema de scraping de diseño de competidores
- Plantillas HTML adaptativas
- Detección mejorada de subservicios
- Enlaces internos inteligentes
"""

import streamlit as st
import pandas as pd
import advertools as adv
import re
import requests
from bs4 import BeautifulSoup
from unidecode import unidecode
from urllib.parse import urlparse, urljoin
from rapidfuzz import fuzz
import time
import io
import hashlib
from collections import Counter

# ============================================
# CONFIGURACIÓN MULTIIDIOMA  
# ============================================

TRANSLATIONS = {
    "es": {
        "title": "🎯 Local SEO Geo-Gap Analyzer",
        "language": "Idioma / Language",
        "service": "Servicio",
        "your_domain": "Tu dominio",
        "competitor": "Competidor",
        "domain_placeholder": "ejemplo.com (sin https://)",
        "analyze_button": "🚀 Analizar Gaps",
        "min_competitors": "❌ Debes ingresar exactamente 3 competidores",
        "invalid_domain": "❌ Dominio inválido",
        "select_saved_domain": "Seleccionar dominio guardado",
        "new_domain": "✏️ Escribir dominio nuevo...",
        "clear_history": "🗑️ Limpiar historial",
        "history_cleared": "Historial borrado",
        "no_saved_domains": "No hay dominios guardados aún",
        "home_zone_detected": "🏠 Zona base detectada",
        "is_correct": "¿Es correcto?",
        "yes": "✓ Sí",
        "no": "✗ No, cambiar",
        "select_city": "Selecciona tu ciudad principal",
        "sitemap_found": "✅ Sitemap detectado",
        "sitemap_robots": "✅ Sitemap en robots.txt",
        "no_sitemap": "⚠️ Sin sitemap (crawling fallback)",
        "domain_error": "❌ No accesible, verifica dominio",
        "analyzing": "Analizando",
        "extracting_urls": "Extrayendo URLs",
        "processing": "Procesando",
        "gaps_found": "Gaps Detectados",
        "strengths_found": "Tus Fortalezas",
        "ties_found": "Empates",
        "low_confidence": "Baja Confianza - Revisar",
        "zone": "Zona",
        "slug": "Slug Sugerido",
        "competitor_urls": "URLs Competidores",
        "competitors_count": "Nº Comps",
        "confidence": "Confianza",
        "search_volume": "Volumen",
        "keyword_difficulty": "KD",
        "traffic": "Tráfico",
        "keywords_ranking": "Keywords",
        "score": "Score",
        "advantage": "Ventaja",
        "strategy": "Estrategia",
        "priority": "Prioridad",
        "confirm": "Confirmar",
        "required_field": "Campo obligatorio",
        "duplicate_domains": "Los dominios deben ser diferentes entre sí",
        "urls_filtered": "URLs filtradas por servicio diferente",
        "critical_priority": "CRÍTICA",
        "high_priority": "ALTA",
        "medium_priority": "MEDIA",
        "low_priority": "BAJA",
        "max_advantage": "MÁXIMA (zona única)",
        "medium_advantage": "MEDIA (baja competencia)",
        "maintain_dominance": "Mantener dominancia. Reforzar contenido y backlinks.",
        "early_advantage": "Ventaja temprana. Invertir en diferenciación.",
        "competitive_market": "Mercado competitivo. Mantener posición con contenido de calidad.",
        "validated_opportunity": "Oportunidad Validada - todos los competidores están ahí",
        "emerging_niche": "Nicho Emergente - mayoría presente",
        "long_tail": "Larga Cola / Experimental - solo uno lo tiene",
        "filter_by_priority": "Filtrar por prioridad",
        "filter_by_competitors": "Filtrar por Nº competidores",
        "search_zone": "Buscar zona",
        "all": "Todas",
        "show_results": "Mostrando",
        "of": "de",
        "results": "resultados",
        "no_gaps_filter": "No hay gaps que coincidan con los filtros",
        "export_csv": "📥 Exportar CSV",
        "api_optional": "📊 API Keywords (Opcional)",
        "enable_api": "Habilitar API",
        "api_provider": "Proveedor",
        "api_key": "API Key",
        "api_key_placeholder": "Pega tu API key aquí",
        "country_code": "País",
        "fetching_metrics": "Obteniendo métricas de API...",
        "using_cache": "✅ Usando datos en caché",
        "add_competitors": "➕ Agregar más competidores (opcional)",
        "competitors_required": "Competidores Obligatorios",
        "competitors_optional": "Competidores Adicionales (Opcional)",
        "total_competitors": "Total competidores",
        "generate_pages": "📄 Generar Páginas",
        "select_gaps": "Seleccionar gaps para crear páginas",
        "preview_template": "👁️ Preview Plantilla",
        "template_selector": "Seleccionar plantilla",
        "base_template": "Plantilla Base",
        "premium_template": "Plantilla Premium",
        "minimal_template": "Plantilla Minimalista",
    },
    "en": {
        "title": "🎯 Local SEO Geo-Gap Analyzer",
        "language": "Idioma / Language",
        "service": "Service",
        "your_domain": "Your domain",
        "competitor": "Competitor",
        "domain_placeholder": "example.com (without https://)",
        "analyze_button": "🚀 Analyze Gaps",
        "min_competitors": "❌ You must enter exactly 3 competitors",
        "invalid_domain": "❌ Invalid domain",
        "select_saved_domain": "Select saved domain",
        "new_domain": "✏️ Enter new domain...",
        "clear_history": "🗑️ Clear history",
        "history_cleared": "History cleared",
        "no_saved_domains": "No saved domains yet",
        "home_zone_detected": "🏠 Home zone detected",
        "is_correct": "Is this correct?",
        "yes": "✓ Yes",
        "no": "✗ No, change",
        "select_city": "Select your main city",
        "sitemap_found": "✅ Sitemap detected",
        "sitemap_robots": "✅ Sitemap in robots.txt",
        "no_sitemap": "⚠️ No sitemap (crawling fallback)",
        "domain_error": "❌ Not accessible, verify domain",
        "analyzing": "Analyzing",
        "extracting_urls": "Extracting URLs",
        "processing": "Processing",
        "gaps_found": "Gaps Detected",
        "strengths_found": "Your Strengths",
        "ties_found": "Ties",
        "low_confidence": "Low Confidence - Review",
        "zone": "Zone",
        "slug": "Suggested Slug",
        "competitor_urls": "Competitor URLs",
        "competitors_count": "# Comps",
        "confidence": "Confidence",
        "search_volume": "Volume",
        "keyword_difficulty": "KD",
        "traffic": "Traffic",
        "keywords_ranking": "Keywords",
        "score": "Score",
        "advantage": "Advantage",
        "strategy": "Strategy",
        "priority": "Priority",
        "confirm": "Confirm",
        "required_field": "Required field",
        "duplicate_domains": "Domains must be different from each other",
        "urls_filtered": "URLs filtered by different service",
        "critical_priority": "CRITICAL",
        "high_priority": "HIGH",
        "medium_priority": "MEDIUM",
        "low_priority": "LOW",
        "max_advantage": "MAXIMUM (unique zone)",
        "medium_advantage": "MEDIUM (low competition)",
        "maintain_dominance": "Maintain dominance. Reinforce content and backlinks.",
        "early_advantage": "Early advantage. Invest in differentiation.",
        "competitive_market": "Competitive market. Maintain position with quality content.",
        "validated_opportunity": "Validated Opportunity - all competitors are there",
        "emerging_niche": "Emerging Niche - majority present",
        "long_tail": "Long Tail / Experimental - only one has it",
        "filter_by_priority": "Filter by priority",
        "filter_by_competitors": "Filter by # competitors",
        "search_zone": "Search zone",
        "all": "All",
        "show_results": "Showing",
        "of": "of",
        "results": "results",
        "no_gaps_filter": "No gaps match the filters",
        "export_csv": "📥 Export CSV",
        "api_optional": "📊 Keywords API (Optional)",
        "enable_api": "Enable API",
        "api_provider": "Provider",
        "api_key": "API Key",
        "api_key_placeholder": "Paste your API key here",
        "country_code": "Country",
        "fetching_metrics": "Fetching API metrics...",
        "using_cache": "✅ Using cached data",
        "add_competitors": "➕ Add more competitors (optional)",
        "competitors_required": "Required Competitors",
        "competitors_optional": "Additional Competitors (Optional)",
        "total_competitors": "Total competitors",
        "generate_pages": "📄 Generate Pages",
        "select_gaps": "Select gaps to create pages",
        "preview_template": "👁️ Preview Template",
        "template_selector": "Select template",
        "base_template": "Base Template",
        "premium_template": "Premium Template",
        "minimal_template": "Minimal Template",
    }
}

# (Continuaré el código en el siguiente mensaje debido a límite de caracteres)
